const columns = [
  {
    name: "FIle Name",
    uid: "filename",
    sortable: true,
    classname: "text-left w-[130px]",
  },
  {
    name: "Last Updated",
    uid: "last_updated",
    sortable: true,
    classname: "text-left w-[145px]",
  },
  {
    name: "Key Date",
    uid: "key_date",
    sortable: true,
    classname: "text-left w-[145px]",
  },
  {
    name: "Uploaded By",
    uid: "uploaded_by",
    sortable: true,
    classname: "w-[109px] text-center",
  },
  {
    name: "Tags",
    uid: "tags",
    sortable: true,
    classname: "w-[147px] text-center",
  },
  { name: "Notes", uid: "notes", sortable: true, classname: "w-[145px]" },
  { name: "Modify", uid: "modify", classname: "w-[96px]" },
  { name: "Actions", uid: "actions", classname: "w-[82px]" },
];

const files = [
  {
    filename: "three.png",
    last_updated: "10-17-24 09:09 PM",
    key_date: "October 27, 2023",
    uploaded_by: "Paul",
    tags: "tag7, tag1, tag5",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "voice.png",
    last_updated: "02-02-24 02:51 AM",
    key_date: "January 13, 2024",
    uploaded_by: "Robert",
    tags: "tag7, tag5, tag8",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "event.png",
    last_updated: "10-06-23 02:31 AM",
    key_date: "March 29, 2024",
    uploaded_by: "Tammy",
    tags: "tag4, tag9, tag3",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "mention.png",
    last_updated: "08-07-23 09:50 PM",
    key_date: "April 19, 2023",
    uploaded_by: "Richard",
    tags: "tag2, tag5, tag3",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "step.png",
    last_updated: "08-29-23 09:34 PM",
    key_date: "March 18, 2023",
    uploaded_by: "Maria",
    tags: "tag2, tag6, tag8",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "home.png",
    last_updated: "11-07-23 06:38 PM",
    key_date: "February 05, 2023",
    uploaded_by: "Crystal",
    tags: "tag2, tag9, tag6",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "other.png",
    last_updated: "01-20-24 04:55 PM",
    key_date: "June 20, 2024",
    uploaded_by: "Jacob",
    tags: "tag6, tag7, tag2",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "here.png",
    last_updated: "02-11-24 02:58 AM",
    key_date: "October 02, 2024",
    uploaded_by: "Laura",
    tags: "tag8, tag5, tag1",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "career.png",
    last_updated: "01-19-23 01:01 AM",
    key_date: "November 18, 2024",
    uploaded_by: "Jill",
    tags: "tag8, tag7, tag5",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "seat.png",
    last_updated: "12-04-24 01:35 PM",
    key_date: "June 19, 2024",
    uploaded_by: "Kristen",
    tags: "tag8, tag7, tag1",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "finish.png",
    last_updated: "12-17-23 08:50 AM",
    key_date: "March 05, 2024",
    uploaded_by: "Kendra",
    tags: "tag1, tag4, tag6",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "better.png",
    last_updated: "07-10-24 10:57 AM",
    key_date: "April 09, 2023",
    uploaded_by: "Shawn",
    tags: "tag5, tag7, tag8",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "news.png",
    last_updated: "08-16-23 06:06 AM",
    key_date: "October 16, 2023",
    uploaded_by: "Adam",
    tags: "tag9, tag5, tag6",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "dog.png",
    last_updated: "07-23-23 01:33 AM",
    key_date: "September 15, 2023",
    uploaded_by: "Gary",
    tags: "tag8, tag4, tag3",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "roamer.png",
    last_updated: "06-04-23 05:56 AM",
    key_date: "October 08, 2023",
    uploaded_by: "Jacob",
    tags: "tag9, tag2, tag1",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "hand.png",
    last_updated: "07-07-23 01:57 AM",
    key_date: "September 06, 2024",
    uploaded_by: "Douglas",
    tags: "tag3, tag8, tag4",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "measure.png",
    last_updated: "01-21-23 06:35 AM",
    key_date: "October 26, 2023",
    uploaded_by: "Jill",
    tags: "tag6, tag3, tag9",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "city.png",
    last_updated: "03-09-23 08:33 AM",
    key_date: "November 11, 2024",
    uploaded_by: "Patrick",
    tags: "tag6, tag3, tag9",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "job.png",
    last_updated: "11-20-24 09:25 PM",
    key_date: "October 15, 2024",
    uploaded_by: "Brittany",
    tags: "tag3, tag7, tag4",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "fish.png",
    last_updated: "12-06-24 12:36 AM",
    key_date: "April 05, 2024",
    uploaded_by: "Sara",
    tags: "tag9, tag8, tag4",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "similar.png",
    last_updated: "08-11-23 04:33 AM",
    key_date: "January 10, 2024",
    uploaded_by: "Susan",
    tags: "tag8, tag7, tag3",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "room.png",
    last_updated: "07-15-23 02:10 PM",
    key_date: "October 04, 2023",
    uploaded_by: "Ryan",
    tags: "tag4, tag2, tag8",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "side.png",
    last_updated: "03-19-23 12:21 AM",
    key_date: "April 28, 2024",
    uploaded_by: "Chris",
    tags: "tag9, tag3, tag8",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "capital.png",
    last_updated: "07-20-23 01:31 AM",
    key_date: "April 26, 2023",
    uploaded_by: "Gary",
    tags: "tag2, tag1, tag9",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "threat.png",
    last_updated: "10-26-23 10:22 PM",
    key_date: "February 20, 2023",
    uploaded_by: "Casey",
    tags: "tag2, tag7, tag5",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "friend.png",
    last_updated: "01-23-23 11:18 AM",
    key_date: "July 10, 2024",
    uploaded_by: "Michael",
    tags: "tag3, tag8, tag7",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "respond.png",
    last_updated: "02-12-24 07:48 PM",
    key_date: "August 26, 2024",
    uploaded_by: "Lindsay",
    tags: "tag4, tag3, tag8",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "animal.png",
    last_updated: "08-16-24 02:20 AM",
    key_date: "February 21, 2023",
    uploaded_by: "Nathan",
    tags: "tag1, tag8, tag4",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "often.png",
    last_updated: "09-14-24 05:34 AM",
    key_date: "August 18, 2024",
    uploaded_by: "Samantha",
    tags: "tag9, tag7, tag8",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "draw.png",
    last_updated: "01-14-24 06:54 AM",
    key_date: "January 19, 2023",
    uploaded_by: "Ashley",
    tags: "tag2, tag5, tag7",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "wish.png",
    last_updated: "05-12-23 06:00 PM",
    key_date: "January 10, 2024",
    uploaded_by: "Joshua",
    tags: "tag7, tag9, tag8",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "position.png",
    last_updated: "07-08-23 02:03 AM",
    key_date: "October 16, 2024",
    uploaded_by: "Andrew",
    tags: "tag5, tag3, tag1",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "late.png",
    last_updated: "10-30-24 04:22 AM",
    key_date: "October 13, 2023",
    uploaded_by: "Heather",
    tags: "tag5, tag4, tag2",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "owner.png",
    last_updated: "12-01-24 01:11 PM",
    key_date: "January 23, 2023",
    uploaded_by: "Heather",
    tags: "tag2, tag7, tag9",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "degree.png",
    last_updated: "12-28-23 11:24 PM",
    key_date: "March 12, 2023",
    uploaded_by: "Timothy",
    tags: "tag7, tag4, tag5",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "account.png",
    last_updated: "04-27-23 10:43 PM",
    key_date: "April 21, 2023",
    uploaded_by: "Justin",
    tags: "tag8, tag5, tag9",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "number.png",
    last_updated: "01-30-24 09:34 AM",
    key_date: "April 08, 2023",
    uploaded_by: "Douglas",
    tags: "tag6, tag9, tag7",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "discussion.png",
    last_updated: "09-12-23 06:36 PM",
    key_date: "August 08, 2023",
    uploaded_by: "Kristen",
    tags: "tag7, tag1, tag3",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "those.png",
    last_updated: "07-17-24 11:41 AM",
    key_date: "June 05, 2023",
    uploaded_by: "Joshua",
    tags: "tag2, tag1, tag3",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "natural.png",
    last_updated: "04-25-23 09:09 PM",
    key_date: "August 08, 2023",
    uploaded_by: "Stephanie",
    tags: "tag4, tag5, tag9",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "cut.png",
    last_updated: "04-09-23 04:05 AM",
    key_date: "March 08, 2024",
    uploaded_by: "Aaron",
    tags: "tag7, tag4, tag3",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "red.png",
    last_updated: "05-22-23 06:54 AM",
    key_date: "October 12, 2023",
    uploaded_by: "Adam",
    tags: "tag4, tag6, tag3",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "simple.png",
    last_updated: "06-09-23 02:56 AM",
    key_date: "February 20, 2023",
    uploaded_by: "Lisa",
    tags: "tag5, tag1, tag7",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "specific.png",
    last_updated: "09-06-23 11:56 AM",
    key_date: "September 24, 2024",
    uploaded_by: "Lindsay",
    tags: "tag8, tag3, tag7",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "administration.png",
    last_updated: "08-18-24 10:50 AM",
    key_date: "October 25, 2024",
    uploaded_by: "Justin",
    tags: "tag2, tag4, tag9",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "drop.png",
    last_updated: "05-20-23 01:05 PM",
    key_date: "October 17, 2024",
    uploaded_by: "Maria",
    tags: "tag4, tag3, tag8",
    notes: "Important document",
    modify: true,
    actions: true,
  },
  {
    filename: "including.png",
    last_updated: "01-07-23 11:34 AM",
    key_date: "July 26, 2024",
    uploaded_by: "Michael",
    tags: "tag5, tag3, tag1",
    notes: "Important document",
    modify: true,
    actions: true,
  },
];

export { columns, files };
